### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by tolu** [nrkno/best-practice#1]
Känns inte helt ok att vi skall ha en "best practice" som bara gäller native apps?

Är tanken att ha folders för olika områden eller hur är det tänkt?

**Comment by ChristianVinterly** [comment]
This repo is for all development at NRK, but we started with native apps. Feel free to add a new section of best practices for other platforms 😄

**Comment by heumn** [comment]
> Är tanken att ha folders för olika områden eller hur är det tänkt?

The reason it is named "best practice" without any platforms mentioned was not an accident. You are more than welcome to start a new one!

![snl-join-us-d-VPcVGQVX5WOMU](https://media3.giphy.com/media/VPcVGQVX5WOMU/giphy.gif)

**Comment by thohalv** [comment]
Please join in and feel free to change "Best practice guide to ~~(at start)~~ programming ~~native apps~~ in NRK"

**Comment by tolu** [comment]
Ok, låt mig sæga det på ett annat sætt.
Tror det ær namnet som gør mig lite un-easy.

_BestPractice_ før mig betyder mycket mer æn en samling linker eller en CodeStyleGuide's.
Och om det ær tanken (linker å styleguides) så har vi før det førsta ett dokumentationssystem som heter Confluence och før det andra tror jag mer på github community power når det kommer til å uppdatere listor och styleguides som 
- [awesome-android](https://github.com/JStumpp/awesome-android)
- [awesome-ios](https://github.com/vsouza/awesome-ios)
- [google code styleguides](https://github.com/google/styleguide)

Så egentligen ær jag orolig før tre saker
- att vi inte anvænder vårt dokumentationssystem
- att namnet på detta repo inte motsvarar innehållet
- att det inte kommer underhållas eller uppdateras och dærfør dø ut

Men please, prove me wrong 😃

**Comment by tolu** [comment]
Angående

> Feel free to add a new section of best practices for other platforms 😄

Och

> You are more than welcome to start a new one!

Så kan jag bara upplysa om att det bara ær Mobil-teamet som har skrivrættigheter till detta repot just nu 😉

**Comment by heumn** [comment]
> att vi inte anvænder vårt dokumentationssystem
> att namnet på detta repo inte motsvarar innehållet
> att det inte kommer underhållas eller uppdateras och dærfør dø ut

Since all of these things describe future scenarios I guess we have to prove you wrong :star2:

Your hunch that something is off base is still really important. We have probably not explained what and why we do this in a sufficient manner. Maybe you have some input over a cup of coffee? Lengthy discussions are still not best done in text unless sufficiently sprinkled with gifs (internet still hasn't fixed human emotions... 💩 )

![snl-join-us-d-VPcVGQVX5WOMU](https://media0.giphy.com/media/3o6Zt7efI3ruag4zEA/200.gif#17)
